### ISSUE TITLE
desc metadata roundtripping error for H2 objects > v1

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/dor-services-app#2895]
i ran into this when running an integration test with this recently added expectation around creating a new version in H2:
https://github.com/sul-dlss/infrastructure-integration-test/commit/a3f00d8dd37ea52ff86731377a850c833b60483a#diff-89992691b97416baa388ca17522ddbed0d314be9607b0496bf6bf85056fd312a

when commenting that out, the test passes against the current SDR `main` branches.

example objects created by the integration test:
https://argo-stage.stanford.edu/view/hv756zn5096
https://argo-stage.stanford.edu/view/gp607vd9550

honeybadger error:  https://app.honeybadger.io/projects/50568/faults/79355918
```
Cocina::RoundtripValidationError: Roundtripping of descriptive metadata unsuccessful. Expected {"title":[{"value":"SUL Logo for heat_of_condensation"}],"contributor":[{"name":[{"structuredValue":[{"value":"Dana","type":"forename"},{"value":"Scully","type":"surname"}]}],"type":"person","status":"primary","role":[{"value":"author","code":"aut","uri":"http://id.loc.gov/vocabulary/relators/aut","source":{"code":"marcrelator","uri":"http://id.loc.gov/vocabulary/relators/"}}]}],"form":[{"structuredValue":[{"value":"Image","type":"type"}],"type":"resource type","source":{"value":"Stanford self-deposit resource types"}},{"value":"still image","type":"resource type","source":{"value":"MODS resource types"}}],"note":[{"value":"A changed abstract for heat_of_condensation logo","type":"summary"},{"value":"Scully, D. (2021). SUL Logo for heat_of_condensation. Stanford Digital Repository. Available at http://sul-purl-stage.stanford.edu/gp607vd9550","type":"preferred citation"}],"subject":[{"value":"Integration test","type":"topic"}],"purl":"http://sul-purl-stage.stanford.edu/gp607vd9550","access":{"accessContact":[{"value":"suntzu@stanford.edu","type":"email","displayLabel":"Contact"}],"digitalRepository":[{"value":"Stanford Digital Repository"}]}} but received {"title":[{"value":"SUL Logo for heat_of_condensation"}],"purl":"https://sul-purl-stage.stanford.edu/gp607vd9550","note":[{"value":"A changed abstract for heat_of_condensation logo","type":"summary"},{"value":"Scully, D. (2021). SUL Logo for heat_of_condensation. Stanford Digital Repository. Available at http://sul-purl-stage.stanford.edu/gp607vd9550","type":"preferred citation"}],"contributor":[{"name":[{"structuredValue":[{"value":"Dana","type":"forename"},{"value":"Scully","type":"surname"}]}],"type":"person","status":"primary","role":[{"source":{"code":"marcrelator","uri":"http://id.loc.gov/vocabulary/relators/"},"uri":"http://id.loc.gov/vocabulary/relators/aut","code":"aut","value":"author"}]}],"subject":[{"value":"Integration test","type":"topic"}],"form":[{"type":"resource type","source":{"value":"Stanford self-deposit resource types"},"structuredValue":[{"value":"Image","type":"type"}]},{"value":"still image","type":"resource type","source":{"value":"MODS resource types"}}],"relatedResource":[{"purl":"http://sul-purl-stage.stanford.edu/gp607vd9550","access":{"digitalRepository":[{"value":"Stanford Digital Repository"}]}}],"access":{"accessContact":[{"value":"suntzu@stanford.edu","type":"email","displayLabel":"Contact"}],"digitalRepository":[{"value":"Stanford Digital Repository"}]}}.
```

```
[PROJECT_ROOT]/app/services/cocina/object_updater.rb:167 :in `validate`
      if has_changed?(:description) && update_descriptive? && Settings.enabled_features.validate_descriptive_roundtrip.update
        result = DescriptionRoundtripValidator.valid_from_cocina?(cocina_object)
        raise RoundtripValidationError, result.failure unless result.success?
      end
    end
[PROJECT_ROOT]/app/services/cocina/object_updater.rb:31 :in `run`
[PROJECT_ROOT]/app/services/cocina/object_updater.rb:16 :in `run`
[PROJECT_ROOT]/app/controllers/objects_controller.rb:45 :in `update` 
```

<img width="1297" alt="Screen Shot 2021-06-29 at 1 15 07 PM" src="https://user-images.githubusercontent.com/7741604/123861578-32b41700-d8dc-11eb-897d-f8f96d2520d9.png">

at present, the objects are stuck in deposit, and sdr-api is continually retrying the update (though that last part will no longer be the case once https://github.com/sul-dlss/sdr-api/pull/325 is merged, since this isn't really a retriable error).

when discussing on slack this morning, @arcadiafalcone observed:
> the roundtrip errors are 1) purl has http vs https and 2) the expect block is missing the relatedResource

**Comment by justinlittman** [comment]
The problem is that the configuration setting for `purl_base_url` incorrectly included `https` instead of `http` for QA and staging. I've corrected this in shared_configs. Fresh deploys should resolve the problem.

**Comment by jmartin-sul** [comment]
i think this might still be occurring.  haven't had a chance to actually look into it, but the `create_object_h2_spec.rb` integration test still seems to fail at the end, and i still see what looks like a relevant DSA roundtripping error corresponding to the test failure.

https://app.honeybadger.io/projects/50568/faults/79355918/01F9FHM9VQKFVZZTQYNDB3WBCD?page=0

> Cocina::RoundtripValidationError: Roundtripping of descriptive metadata unsuccessful. Expected {"title":[{"value":"SUL Logo for pago_pago"}],"contributor":[{"name":[{"structuredValue":[{"value":"Dana","type":"forename"},{"value":"Scully","type":"surname"}]}],"type":"person","status":"primary","role":[{"value":"author","code":"aut","uri":"http://id.loc.gov/vocabulary/relators/aut","source":{"code":"marcrelator","uri":"http://id.loc.gov/vocabulary/relators/"}}]}],"form":[{"structuredValue":[{"value":"Image","type":"type"}],"type":"resource type","source":{"value":"Stanford self-deposit resource types"}},{"value":"still image","type":"resource type","source":{"value":"MODS resource types"}}],"note":[{"value":"A changed abstract for pago_pago logo","type":"summary"},{"value":"Scully, D. (2021). SUL Logo for pago_pago. Stanford Digital Repository. Available at http://sul-purl-stage.stanford.edu/rq818tq5059","type":"preferred citation"}],"subject":[{"value":"Integration test","type":"topic"}],"purl":"http://sul-purl-stage.stanford.edu/rq818tq5059","access":{"accessContact":[{"value":"suntzu@stanford.edu","type":"email","displayLabel":"Contact"}],"digitalRepository":[{"value":"Stanford Digital Repository"}]}} but received {"title":[{"value":"SUL Logo for pago_pago"}],"purl":"https://sul-purl-stage.stanford.edu/rq818tq5059","note":[{"value":"A changed abstract for pago_pago logo","type":"summary"},{"value":"Scully, D. (2021). SUL Logo for pago_pago. Stanford Digital Repository. Available at http://sul-purl-stage.stanford.edu/rq818tq5059","type":"preferred citation"}],"contributor":[{"name":[{"structuredValue":[{"value":"Dana","type":"forename"},{"value":"Scully","type":"surname"}]}],"type":"person","status":"primary","role":[{"source":{"code":"marcrelator","uri":"http://id.loc.gov/vocabulary/relators/"},"uri":"http://id.loc.gov/vocabulary/relators/aut","code":"aut","value":"author"}]}],"subject":[{"value":"Integration test","type":"topic"}],"form":[{"type":"resource type","source":{"value":"Stanford self-deposit resource types"},"structuredValue":[{"value":"Image","type":"type"}]},{"value":"still image","type":"resource type","source":{"value":"MODS resource types"}}],"relatedResource":[{"purl":"http://sul-purl-stage.stanford.edu/rq818tq5059","access":{"digitalRepository":[{"value":"Stanford Digital Repository"}]}}],"access":{"accessContact":[{"value":"suntzu@stanford.edu","type":"email","displayLabel":"Contact"}],"digitalRepository":[{"value":"Stanford Digital Repository"}]}}.

the switch to `http` for purl does seem to have taken effect after a deploy yesterday (`http://sul-purl-stage.stanford.edu/rq818tq5059`)

**Comment by justinlittman** [comment]
Verified that the setting had NOT been changed on stage. I re-deployed and verified that the setting had been changed. Try again?

**Comment by jmartin-sul** [comment]
> Verified that the setting had NOT been changed on stage. I re-deployed and verified that the setting had been changed. Try again?

sorry, my bad!  i had looked at the deployment times and thought the shared_configs change had made it out by inferring from that, but i must've been wrong.  hadn't looked directly at the setting.

just re-ran the test, and all's well, closing.
